apiVersion: v1
kind: ServiceAccount
metadata:
  name: rancher
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rancher
subjects:
- kind: ServiceAccount
  name: rancher
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Secret
metadata:
  name: rancher-credentials
  namespace: kube-system
type: Opaque
data:
  url: ""
  access-key: ""
  secret-key: ""

---

apiVersion: v1
kind: Pod
metadata:
  name: cluster-register
  namespace: kube-system
spec:
  serviceAccountName: rancher
  restartPolicy: Never
  containers:
    - name: cluster-register
      image: joshwget/cluster-register
      volumeMounts:
      - name: rancher-credentials
        mountPath: /rancher-credentials
        readOnly: true
  volumes:
  - name: rancher-credentials
    secret:
      secretName: rancher-credentials
